# Generated by Django 4.1.3 on 2023-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Soal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_kelas", models.CharField(max_length=10)),
                ("id_mapel", models.CharField(max_length=10)),
                ("soal", models.TextField()),
                ("kunci_jawaban", models.TextField()),
            ],
            options={
                "db_table": "tb_soal",
            },
        ),
    ]
