# Generated by Django 4.2.1 on 2023-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='id_user',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_kelas',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_mapel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
