# Generated by Django 3.0.5 on 2023-06-28 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0002_auto_20230628_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kdsoal',
            fields=[
                ('kode_soal', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_ujian', models.CharField(max_length=255)),
                ('deskripsi_ujian', models.TextField()),
                ('id_mapel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jawaban',
            options={},
        ),
        migrations.AddField(
            model_name='soal',
            name='tgl_input',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
